sudo: required
dist: trusty

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - COMPILER=g++-6
        - CONFIGURATION=release
    - os: linux
      compiler: gcc
      env:
        - COMPILER=g++-6
        - CONFIGURATION=debug
    - os: osx
      compiler: clang
      env:
        - COMPILER=clang++
        - CONFIGURATION=release
    - os: osx
      compiler: clang
      env:
        - COMPILER=clang++
        - CONFIGURATION=debug

before_install:
  - wget "https://github.com/premake/premake-core/releases/download/v5.0.0-alpha11/premake-5.0.0-alpha11-linux.tar.gz"
  - tar -xvf premake-5.0.0-alpha11-linux.tar.gz

install:
  - ./premake5 gmake

script:
  - export CXX=$COMPILER
  - make -C build/gmake/ config=$CONFIGURATION Test
  - ./build/gmake/bin/$CONFIGURATION/Test
