sudo: required

language: cpp

os:
  - linux
  - osx

dist: trusty

compiler:
  - clang
  - gcc

env:
  - CONFIGURATION=release
  - CONFIGURATION=debug

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo apt-get update --yes
  - sudo apt-get install gcc-6 g++-6 --yes
  - git clone https://github.com/premake/premake-core.git
  - cd premake-core
  - git submodule init
  - git submodule update
  - make -f Bootstrap.mak $TRAVIS_OS_NAME
  - cp bin/release/premake5 ../premake5
  - cd ../

install:
  - ./premake5 gmake

script:
  - make -C build/gmake/ config=$CONFIGURATION Test
  - ./build/gmake/bin/$CONFIGURATION/Test
